version: "3.8"

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    image: vidly_web:1
    restart: unless-stopped
  api:
    build: ./backend
    ports:
      - 3001:3001
    image: vidly_api:1
    environment:
      DB_URL: mongodb://db/vidly
    restart: unless-stopped
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
    restart: unless-stopped
volumes: 
  vidly: 